networks:
  ict3914-final-year-project_rabbit-network:
    external: true

services:
  producer-app:
    build:
      context: ./pharma-hybrid-rabbitmq-producer
      dockerfile: Dockerfile
    container_name: producer-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - ict3914-final-year-project_rabbit-network
    depends_on:
      axon-server:
        condition: service_healthy

  consumer-app:
    build:
      context: ./pharma-hybrid-rabbitmq-consumer
      dockerfile: Dockerfile
    container_name: consumer-app
    env_file:
      - .env
    networks:
      - ict3914-final-year-project_rabbit-network
    restart: always
    depends_on:
      axon-server:
        condition: service_healthy

  axon-server:
    image: axoniq/axonserver
    container_name: axon-server
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - ict3914-final-year-project_rabbit-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8024"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ict3914-final-year-project_rabbit-network
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ict3914-final-year-project_rabbit-network

volumes:
  pgdata:
